version: '3'
services:

  web:
    image: nginx:alpine
    container_name: php-recommend
    volumes:
    - ./docs:/var/www/html/php-recommend/:ro
    - ./nginx.conf:/etc/nginx/conf.d/default.conf
    labels:
      SERVICE_NAME: php-recommend
